#!/usr/bin/python3 -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

def log(string):
  sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = int(sys.argv[1])
print(UDP_IP, UDP_PORT)
# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
#UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

# Now listen for packets
while True:
  result = sock.recvfrom(MSG_SIZE)
  print(result)
  # If nothing is ready, we hit the timeout
  if result:
    (data, addr) = result

    try:
      seq = data[0:2]
      data = data[2:].decode("ascii") 

      # If the EOF flag is set, exit
      if (int.from_bytes(seq, "little") == 0):
        log("[completed]")
        sys.exit(0)

      # If there is data, we accept it and print it out
      else:
        # If we receive data, we assume it's in-order
        # You will need to do much more here
        log("[recv data] " + str(data) + " (" + str(len(data)) + ") ACCEPTED (in-order)")
        sys.stdout.write(data)

      # Send back an ack to the sender
      msg = seq 
      #log("ABOUT TO SEND " + msg)
      if sock.sendto(msg, addr) < len(msg):
        log("[error] unable to fully send packet")

    except (ValueError, KeyError, TypeError) as e:
      log("[recv corrupt packet]")
      raise e
  else:
    log("[error] timeout")
    sys.exit(-1)
