#!/usr/bin/python3 -u
#
# CS3700, Spring 2015
# Project 2 Starter Code
#

import sys
import socket
import time
import datetime
import select
import json

def log(string):
    sys.stderr.write(datetime.datetime.now().strftime("%H:%M:%S.%f") + " " + string + "\n")

MSG_SIZE = 1500
TIMEOUT = 30

# Bind to localhost and an ephemeral port
UDP_IP = "127.0.0.1"
UDP_PORT = int(sys.argv[1])
#print(UDP_IP, UDP_PORT)
# Set up the socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM) 
sock.bind((UDP_IP, UDP_PORT))
sock.settimeout(TIMEOUT)

# Get port we bound to
#UDP_PORT = sock.getsockname()[1]
log("[bound] " + str(UDP_PORT))

num_pckts = 0
packets = {}

# Now listen for packets
while True:
    try:
        result = sock.recvfrom(MSG_SIZE)
    except OSError:
        log("timeout")
        sys.exit(-1)
    #print(result)
    # If nothing is ready, we hit the timeout
    if result:
        (data, addr) = result
        seq = int.from_bytes(data[0:2], "little")
        num_pckts = int.from_bytes(data[2:4], "little")
        log("[recv data] " + str(seq) + " " + str(num_pckts))
        data = data[4:].decode("ascii")

        # If the EOF flag is set, exit
        #if (int.from_bytes(seq, "little") == 0):
        #    log("[completed]")
        #    sys.exit(0)

        # If there is data, we accept it and print it out
        #else:
            # If we receive data, we assume it's in-order
            # You will need to do much more here
            #log("[recv data] " + str(data) + " (" + str(len(data)) + ") ACCEPTED (in-order)")
            #sys.stdout.write(data)

        # Send back an ack to the sender
        msg = seq.to_bytes(2, "little")
        log("ABOUT TO SEND " + str(int.from_bytes(msg, "little")))
        if sock.sendto(msg, addr) < len(msg):
            log("[error] unable to fully send packet")

        #add data to dict and check if finished
        packets[str(seq)] = data
        if len(packets) == num_pckts:
            log("[completed]")
            #complete_data = ""
            #for i in range(0, num_pckts):
            #    complete_data += packets[str(i)]
            #    print("asdf", packets[str(i)])
            complete_data = "".join([ packets[str(i)] for i in range(0, num_pckts) ])
            sys.stdout.write(complete_data)
            sys.exit(0)
    else:
        log("[error] timeout")
        sys.exit(-1)
